# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustytools_wrappers", use_symbols = TRUE, package_name = "rustytools")

#' @docType package
#' @usage NULL
#' @useDynLib rustytools, .registration = TRUE
NULL

#' @export
getconsensus <- function(rstring, index_add) invisible(.Call(wrap__getconsensus, rstring, index_add))


# nolint end
